### ISSUE TITLE
Assets added, but font is not downloaded 

### ISSUE THREAD

**Issue by lologhi** [scottdejonge/map-icons#33]
Hello!
I don't have any error in the console, the map-icons.css is well loaded with the `@font-face` (.js loaded too), but the font is not loaded. So I have the markers, but nothing on it... 
Can you think of something?
Thanks a lot! No public access to this problematic page, but should be possible soon)

**Comment by scottdejonge** [comment]
Make sure your font paths are correct and that the CSS is being loaded. Maybe check the network tab in your browser's developer tools to see if the fonts are being requested.

Sorry I can't provide any further information without context, maybe providing a CodePen or something.

**Comment by lologhi** [comment]
CSS is loaded, and path seems good to me :

On a CSS file like that `https://local.villa-bali.com/css/front_map-icons_3.css`, I have :  

```css
@font-face {
	font-family: 'map-icons';
	src:url('../vendor/map-icons/dist/fonts/map-icons.eot');
	src:url('../vendor/map-icons/dist/fonts/map-icons.eot#iefix') format('embedded-opentype'),
		url('../vendor/map-icons/dist/fonts/map-icons.ttf') format('truetype'),
		url('../vendor/map-icons/dist/fonts/map-icons.woff') format('woff'),
		url('../vendor/map-icons/dist/fonts/map-icons.svg#map-icons') format('svg');
	font-weight: normal;
	font-style: normal;
}
```

And `https://local.villa-bali.com/css/../vendor/map-icons/dist/fonts/map-icons.eot` is working for me.

But there is no request in the network tab. So problem might come from somewhere else. I was not able to easily create a CodePen, so I'll wait to put my page in an accessible location...
